### ISSUE TITLE
Implement code for Weather Station

### ISSUE THREAD

**Issue by joschi36** [zeezee300/openwms#2]
I've got the Blinds at my home working with your code. Thank you for that.

But I think the weather station code isn't implemented yet. Is that right, or am I missing something?

**Comment by zeezee300** [comment]
Yes, you're right. 
Unfortunately I don't have a weather station yet, so I couldn't complete the code yet.

**Comment by Pferdebockwurst** [comment]
I can give you a weather station if you like. But you would have to send it back to me.

**Comment by zeezee300** [comment]
@ Pferdebockwurst
Thank you so much for trusting me :-)
How long do I have for the code implementation?
Since I only find time on the weekend and the message structure is not very well documented, the development and testing will probably take some time.

**Comment by joschi36** [comment]
I think the implementation is easy.
The weather station always broadcasts its data all X seconds.
Problem is I‘m not very good in Java, but i could test the code at my home.

```
7080: Weather Broadcast
			Sending direction: 	 ???
			Receiving direction: SCS=r  , No Parameter, below Payload

			Payload Structure:
			| ??? | Wind m/s   | Lumen 1    | ???    | Lumen 2    | ??? | Rain       | Temperature | ???                                            |
			-----------------------------------------------------------------------------------------------------------------------------------------
			| 00  | 1 Byte HEX | 1 Byte HEX | FFFFFF | 1 Byte HEX | FF  | 1 Byte Hex | 1 Byte Hex  | FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF |

			        | Possible Values
			----------------------------
			Lumen 1 | 00, 02-FF
			Lumen 2 | if Lumen 1 == 0: 00-FA
			        | else: FA
			Rain    | 00: No Rain
				    	| C8: Rain
		  Temp.   | 00-FF: Temperature in °Celsius * 10
					    | Currently no Idea how negative Temperatures and Temperatures above 25.4°C are handled.
			Wind    | 00-19???: integer m/s```

If more information is needed feel free to write me. 
Later when I‘m back at Home, I can send a lot of examples packets.

**Comment by Pferdebockwurst** [comment]
@zeezee300 I can give you the weather station as long as you need it. It's the more expensive one, without the solar panel. I'm in Germany, text me if you like, I'd be happy to help.

**Comment by zeezee300** [comment]
@Pferdebockwurst 
how can I contact you?

**Comment by Pferdebockwurst** [comment]
@zeezee300 Please send a private message to Eberhart in the iobroker forum. That way we can exchange personal data.

**Comment by zeezee300** [comment]
> 
> 
> @zeezee300 Please send a private message to Eberhart in the iobroker forum. That way we can exchange personal data.

unfortunately this function is no longer available in that forum, only chat is possible

**Comment by zeezee300** [comment]
I have extended the code for the weather-staion, but at first only for the channels rain (on/off), temperature and wind.
I couldn't test it because I don't have a weather station yet, so I just uploaded a test version of the compiled openhab bindings `org.openhab.binding.openwms-2.4.0 SNAPSHOT only for tests.jar` - no code.
I took the calculation of the values from the iobroker forum; however, I suspect that the temperature values are not calculated correctly (they are probably at least 3 degrees too low).
But this still has to be tested, checked and verified.

Also still missing is the regular status query, the automatic detection and if necessary the setting of new limit values of the weather station.

**Comment by Pferdebockwurst** [comment]
@zeezee300 Hmm can you give me any e-mail address, I will message you there.

**Comment by zeezee300** [comment]
> 
> @zeezee300 Hmm can you give me any e-mail address, I will message you there.

Pls. send a message to rainer300 at the openhab forum:

> https://community.openhab.org/

**Comment by Pferdebockwurst** [comment]
Done.
