### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by MiCi0** [zeezee300/openwms#3]
Hi, 

placing the file into addons folder does not start the installation. I've tried it manually through karaf by  bundle:install and pasting the link and it gives me an error: org.osgi.framework.BundeException Error reading bundle content

Any idead to solve this?

Thanks & Regards
Mic

**Comment by zeezee300** [comment]
@MiCi0 
Which openhab version do you have?
The current jar file is for the new version 2.5.0 (a stable Version 2.4.0 is also uploaded)

Maybe you can reboot or try the following: 
Go to karaf and type:
`feature:install openhab-transport-serial`

**Comment by MiCi0** [comment]
I do have a freshly installed 2.4.0 from the apt repository 

Installed the Transport serial but still seeing the same issue after restart

**Comment by zeezee300** [comment]
@MiCi0 
Please copy and paste the complete error message.

I suspect the jar file is not in the correct addons folder or the file permissions are not set correctly.

**Comment by MiCi0** [comment]
@zeezee300 

I did place it into /usr/share/openhab2/addon and did the chown openhab:openhab for the file. restarted the service no result. also the openhab.log does not show anything in regards to permission  error

If i got to karaf and execute 

bundle:install https://github.com/zeezee300/openwms/blob/master/org.openhab.binding.openwms_2.4.0.jar


it gives me

Bundle IDs:
Error executing command: Error installing bundles:
        Unable to install bundle https://github.com/zeezee300/openwms/blob/master/org.openhab.binding.openwms_2.4.0.jar: org.osgi.framework.BundleException: Error occurred installing a bundle

thanks for your help!
it give

**Comment by zeezee300** [comment]
@MiCi0 
Pls just place the jar-File into addons folder, without stopping Openhab. If this doesn't work try 

1. Stop OH if it is running.
2. Delete the contents of /var/lib/openhab2/cache and /var/lib/openhab2/tmp folders. For manual installations these folders are in your OH home folder under userdata. DO NOT DELETE THE FOLDERS THEMSELVES, JUST THE CONTENTS.
3. Start OH

**Comment by MiCi0** [comment]
@zeezee300
I gave everything a try. It does not show up. 

I even took a new SD Card freshly installed raspbian, still the same - does not do anything. Is there somehting else wrong with my settings? permissions are given to the file placed in addons folder. Also the log does not show anything different than before.

**Comment by zeezee300** [comment]
@MiCi0 
No, special settings are not required.
It sounds strange - but other bindings (f.e. the rfxcom binding) are easily an correctly installed when you copy them into the addons folder?

Did you download the jar-file one more time (if the first download was corrupt)?

**Comment by MiCi0** [comment]
@zeezee300 

Yip did download it once more, via windows, transfered the file with filezilla and moved it to the right folder. Did a restart of OH and got an error listed in the openhab.log. Went to karaf installed the transport serial feature, restarted again and voila the binding was visible :-)

Thank you so much for your help. Now im fiighting with this:

2019-09-09 19:16:48.554 [ERROR] [openwms.handler.OpenWMSBridgeHandler] - Connection to OpenWMS transceiver failed
gnu.io.NoSuchPortException: null
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:273) ~[?:?]

**Comment by zeezee300** [comment]
@MiCi0 
The logging should be a little longer...
I suspect this error occurred after creating a bridge - right?
However, the error message indicates that the given port is not available and the warema USB stick is not addressed correctly.

**Comment by MiCi0** [comment]
Yes, sorry - it got somehow cut off. I've been searching google and added the openhab user to the dialout & tty group. The error message is different now. Does it effect OH if I'm running a Texas instruments zigbee stick in paralell for ioBroker? The used port is 100% correct. 

2019-09-09 22:03:48.024 [ERROR] [openwms.handler.OpenWMSBridgeHandler] - Con$
gnu.io.UnsupportedCommOperationException: Invalid Parameter
at gnu.io.RXTXPort.setSerialPortParams(RXTXPort.java:212) ~[?:?]
at org.openhab.binding.openwms.connector.OpenWMSSerialConnector.conn$
at org.openhab.binding.openwms.handler.OpenWMSBridgeHandler.connect($
at org.openhab.binding.openwms.handler.OpenWMSBridgeHandler.lambda$0$
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.jav$
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) $
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureT$
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureT$
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecu$
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExec$
at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by zeezee300** [comment]
@MiCi0 
In my opinion, it is definitely a serial port problem and not an issue of the binding.
What hardware are you using?
Have you actually used the USB stick successfully with other software (f.e. realterm)? 
Unfortunately I only can give you the hint to check the permissions (dialout) and the serial.debug_rate (128000 baut) again.

**Comment by MiCi0** [comment]
@zeezee300

In that case I woudl say, lets close off the topic. Many many thanks for your patience and help.

Where can I change/see  the bautrate?

**Comment by zeezee300** [comment]
@MiCi0 
You are welcome.
I would recommend to test the serial port and also the function of the USB stick with a terminal program (f.e. realterm).

Send the following command to the stick:   {G}

If the stick answers, then you can be sure that the communication is ok.
